Put
wbarendr/Webserv pull request #21
Opened 2021-03-22 18:09 UTC by wbarendr

2021-03-22 18:23 UTC, borispeeters requested changes
remove .vscode, then I think we can merge

2021-03-23 00:15 UTC, borispeeters approved these changes

2021-03-23 10:15 UTC, tomoliv30 requested changes

2021-03-23 10:15 UTC, tomoliv30 commented on srcs/RequestHandler.cpp
> +			if (real_path.back() == '/' || (stat(real_path.c_str(), &this->m_statbuf) && S_ISDIR(this->m_statbuf.st_mode)))
std::string::back is c++11, throws compilation error on my end, real_path[real_path.size() - 1] is a work around

2021-03-23 10:15 UTC, tomoliv30 commented on srcs/RequestHandler.cpp
> +	const char *m_file = this->m_request_data->m_real_path.substr(this->m_request_data->m_real_path.find_last_of('/') + 1).c_str();
Doesn't compile because the object backing the pointer  (result of substr) will be destroyed at the end of the full expression (const char *m_file =..)
std::string m_file = real_path.substr() ... and replacing following occurrences by m_file or m_file.str() when needed is a work around.
Even better, if I am not mistaken, is to use this->m_request_data->m_file, which is already calculated in handleMetadata line 388.

2021-03-23 13:55 UTC, wbarendr commented on srcs/RequestHandler.cpp
> +	const char *m_file = this->m_request_data->m_real_path.substr(this->m_request_data->m_real_path.find_last_of('/') + 1).c_str();
Yeah I first was using the one calculated before, but in some cases this was giving an error

2021-03-23 13:55 UTC, wbarendr commented on srcs/RequestHandler.cpp
> +	const char *m_file = this->m_request_data->m_real_path.substr(this->m_request_data->m_real_path.find_last_of('/') + 1).c_str();
not giving the actually file name

2021-03-23 14:57 UTC, merged